-- Add migration script here
-- public.machine_users definition

-- Drop table
-- DROP TABLE public.machine_users;

CREATE TABLE public.machine_users (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	machine_code varchar(255) NOT NULL, -- 机器码
	user_uuid uuid NULL, -- 用户UUID
	platform varchar(50) NULL, -- 平台
	bind_time timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 绑定时间
	status varchar(20) DEFAULT 'active'::character varying NOT NULL, -- 状态
	version_info jsonb NULL, -- 版本信息（JSON格式）
	hardware_hash varchar(255) NULL, -- 硬件哈希
	hardware_raw text NULL, -- 硬件原始信息
	allow boolean DEFAULT true NOT NULL, -- 是否允许使用
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 创建时间
	updated_at timestamptz NULL, -- 更新时间
	CONSTRAINT machine_users_pk PRIMARY KEY (id)
);

CREATE INDEX machine_users_machine_code_idx ON public.machine_users USING btree (machine_code);
CREATE INDEX machine_users_user_uuid_idx ON public.machine_users USING btree (user_uuid);
CREATE INDEX machine_users_status_idx ON public.machine_users USING btree (status);
CREATE INDEX machine_users_platform_idx ON public.machine_users USING btree (platform);

-- Column comments
COMMENT ON COLUMN public.machine_users.id IS '主键ID';
COMMENT ON COLUMN public.machine_users.machine_code IS '机器码';
COMMENT ON COLUMN public.machine_users.user_uuid IS '用户UUID';
COMMENT ON COLUMN public.machine_users.platform IS '平台';
COMMENT ON COLUMN public.machine_users.bind_time IS '绑定时间';
COMMENT ON COLUMN public.machine_users.status IS '状态';
COMMENT ON COLUMN public.machine_users.version_info IS '版本信息（JSON格式，存储versions表的信息）';
COMMENT ON COLUMN public.machine_users.hardware_hash IS '硬件哈希';
COMMENT ON COLUMN public.machine_users.hardware_raw IS '硬件原始信息';
COMMENT ON COLUMN public.machine_users.allow IS '是否允许使用';
COMMENT ON COLUMN public.machine_users.created_at IS '创建时间';
COMMENT ON COLUMN public.machine_users.updated_at IS '更新时间';

