-- Add migration script here
-- public.version_types definition

-- Drop table
-- DROP TABLE public.version_types;

CREATE TABLE public.version_types (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	type_code varchar(50) NOT NULL, -- 类型代码
	type_name varchar(100) NOT NULL, -- 类型名称
	description text NULL, -- 描述
	sort_order int4 DEFAULT 0 NULL, -- 排序顺序
	is_active bool DEFAULT true NOT NULL, -- 是否激活
	CONSTRAINT version_types_pk PRIMARY KEY (id),
	CONSTRAINT version_types_type_code_unique UNIQUE (type_code)
);
CREATE UNIQUE INDEX version_types_type_code_idx ON public.version_types USING btree (type_code);

-- Column comments
COMMENT ON COLUMN public.version_types.id IS '主键ID';
COMMENT ON COLUMN public.version_types.type_code IS '类型代码';
COMMENT ON COLUMN public.version_types.type_name IS '类型名称';
COMMENT ON COLUMN public.version_types.description IS '描述';
COMMENT ON COLUMN public.version_types.sort_order IS '排序顺序';
COMMENT ON COLUMN public.version_types.is_active IS '是否激活';

