-- Add migration script here
-- public.maintenances definition

-- Drop table
-- DROP TABLE public.maintenances;

CREATE TABLE public.maintenances (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	name varchar(100) NOT NULL, -- 维护名称
	description text NULL, -- 维护描述
	status varchar(20) NOT NULL, -- 状态
	start_time timestamptz NOT NULL, -- 开始时间
	end_time timestamptz NOT NULL, -- 结束时间
	maintenance_type varchar(20) NOT NULL, -- 维护类型
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 创建时间
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 更新时间
	CONSTRAINT maintenances_pk PRIMARY KEY (id)
);
CREATE INDEX maintenances_status_idx ON public.maintenances USING btree (status);
CREATE INDEX maintenances_time_idx ON public.maintenances USING btree (start_time, end_time);
CREATE INDEX maintenances_type_idx ON public.maintenances USING btree (maintenance_type);

-- Column comments
COMMENT ON COLUMN public.maintenances.id IS '主键ID';
COMMENT ON COLUMN public.maintenances.name IS '维护名称';
COMMENT ON COLUMN public.maintenances.description IS '维护描述';
COMMENT ON COLUMN public.maintenances.status IS '状态';
COMMENT ON COLUMN public.maintenances.start_time IS '开始时间';
COMMENT ON COLUMN public.maintenances.end_time IS '结束时间';
COMMENT ON COLUMN public.maintenances.maintenance_type IS '维护类型';
COMMENT ON COLUMN public.maintenances.created_at IS '创建时间';
COMMENT ON COLUMN public.maintenances.updated_at IS '更新时间';

