-- Add migration script here
-- public.gray_resources definition

-- Drop table
-- DROP TABLE public.gray_resources;

CREATE TABLE public.gray_resources (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	gray_release_id int4 NOT NULL, -- 灰度发布ID
	version_id int4 NOT NULL, -- 版本ID
	sort_order int4 DEFAULT 0 NOT NULL, -- 排序顺序
	CONSTRAINT gray_resources_pk PRIMARY KEY (id),
	CONSTRAINT gray_resources_gray_release_id_fk FOREIGN KEY (gray_release_id) REFERENCES public.gray_releases(id) ON DELETE CASCADE,
	CONSTRAINT gray_resources_version_id_fk FOREIGN KEY (version_id) REFERENCES public.versions(id)
);
CREATE INDEX gray_resources_gray_release_id_idx ON public.gray_resources USING btree (gray_release_id);
CREATE INDEX gray_resources_version_id_idx ON public.gray_resources USING btree (version_id);

-- Column comments
COMMENT ON COLUMN public.gray_resources.id IS '主键ID';
COMMENT ON COLUMN public.gray_resources.gray_release_id IS '灰度发布ID';
COMMENT ON COLUMN public.gray_resources.version_id IS '版本ID';
COMMENT ON COLUMN public.gray_resources.sort_order IS '排序顺序';

