-- Add migration script here
-- public.versions definition

-- Drop table
-- DROP TABLE public.versions;

CREATE TABLE public.versions (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	type_id int4 NOT NULL, -- 版本类型ID
	resource_name varchar(100) NOT NULL, -- 资源名称
	version varchar(50) NOT NULL, -- 版本号
	name varchar(200) NULL, -- 版本名称
	notes text NULL, -- 更新说明
	platform varchar(50) NULL, -- 平台
	url text NULL, -- 下载链接
	hash varchar(255) NULL, -- 文件哈希
	signature varchar(255) NULL, -- 签名
	install_path text NULL, -- 安装路径
	file_size int4 NULL, -- 文件大小
	is_latest bool DEFAULT false NOT NULL, -- 是否最新版本
	status varchar(20) DEFAULT 'active'::character varying NOT NULL, -- 状态
	pub_date timestamptz NULL, -- 发布时间
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 创建时间
	updated_at timestamptz NULL, -- 更新时间
	deleted_at timestamptz NULL, -- 删除时间
	CONSTRAINT versions_pk PRIMARY KEY (id),
	CONSTRAINT versions_type_id_fk FOREIGN KEY (type_id) REFERENCES public.version_types(id)
);
CREATE INDEX versions_type_id_idx ON public.versions USING btree (type_id);
CREATE INDEX versions_resource_name_idx ON public.versions USING btree (resource_name);
CREATE INDEX versions_status_idx ON public.versions USING btree (status);
CREATE INDEX versions_is_latest_idx ON public.versions USING btree (is_latest);

-- Column comments
COMMENT ON COLUMN public.versions.id IS '主键ID';
COMMENT ON COLUMN public.versions.type_id IS '版本类型ID';
COMMENT ON COLUMN public.versions.resource_name IS '资源名称';
COMMENT ON COLUMN public.versions.version IS '版本号';
COMMENT ON COLUMN public.versions.name IS '版本名称';
COMMENT ON COLUMN public.versions.notes IS '更新说明';
COMMENT ON COLUMN public.versions.platform IS '平台';
COMMENT ON COLUMN public.versions.url IS '下载链接';
COMMENT ON COLUMN public.versions.hash IS '文件哈希';
COMMENT ON COLUMN public.versions.signature IS '签名';
COMMENT ON COLUMN public.versions.install_path IS '安装路径';
COMMENT ON COLUMN public.versions.file_size IS '文件大小';
COMMENT ON COLUMN public.versions.is_latest IS '是否最新版本';
COMMENT ON COLUMN public.versions.status IS '状态';
COMMENT ON COLUMN public.versions.pub_date IS '发布时间';
COMMENT ON COLUMN public.versions.created_at IS '创建时间';
COMMENT ON COLUMN public.versions.updated_at IS '更新时间';
COMMENT ON COLUMN public.versions.deleted_at IS '删除时间';

