-- Add migration script here
-- Create machine_tags and machine_user_tags tables for tag management

-- Drop tables (for development)
-- DROP TABLE public.machine_user_tags CASCADE;
-- DROP TABLE public.machine_tags CASCADE;

-- Create machine_tags table
CREATE TABLE public.machine_tags (
    id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    tag_name varchar(100) NOT NULL, -- 标签名称
    description text NULL, -- 标签描述
    category varchar(50) NULL, -- 标签分类
    is_active boolean DEFAULT true NOT NULL, -- 是否激活
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 创建时间
    CONSTRAINT machine_tags_pk PRIMARY KEY (id),
    CONSTRAINT machine_tags_tag_name_unique UNIQUE (tag_name)
);

-- Create machine_user_tags table (association table)
CREATE TABLE public.machine_user_tags (
    id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    machine_user_id int4 NOT NULL, -- 机器用户ID
    tag_id int4 NOT NULL, -- 标签ID
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 创建时间
    CONSTRAINT machine_user_tags_pk PRIMARY KEY (id),
    CONSTRAINT machine_user_tags_machine_user_id_fk FOREIGN KEY (machine_user_id) REFERENCES public.machine_users(id) ON DELETE CASCADE,
    CONSTRAINT machine_user_tags_tag_id_fk FOREIGN KEY (tag_id) REFERENCES public.machine_tags(id) ON DELETE CASCADE,
    CONSTRAINT machine_user_tags_unique UNIQUE (machine_user_id, tag_id)
);

-- Create indexes for performance
CREATE INDEX machine_tags_tag_name_idx ON public.machine_tags USING btree (tag_name);
CREATE INDEX machine_tags_is_active_idx ON public.machine_tags USING btree (is_active);
CREATE INDEX machine_user_tags_machine_user_id_idx ON public.machine_user_tags USING btree (machine_user_id);
CREATE INDEX machine_user_tags_tag_id_idx ON public.machine_user_tags USING btree (tag_id);

-- Column comments
COMMENT ON TABLE public.machine_tags IS '机器标签主表';
COMMENT ON TABLE public.machine_user_tags IS '机器用户标签关联表';

COMMENT ON COLUMN public.machine_tags.id IS '主键ID';
COMMENT ON COLUMN public.machine_tags.tag_name IS '标签名称（唯一）';
COMMENT ON COLUMN public.machine_tags.description IS '标签描述';
COMMENT ON COLUMN public.machine_tags.category IS '标签分类';
COMMENT ON COLUMN public.machine_tags.is_active IS '是否激活';
COMMENT ON COLUMN public.machine_tags.created_at IS '创建时间';

COMMENT ON COLUMN public.machine_user_tags.id IS '主键ID';
COMMENT ON COLUMN public.machine_user_tags.machine_user_id IS '机器用户ID';
COMMENT ON COLUMN public.machine_user_tags.tag_id IS '标签ID';
COMMENT ON COLUMN public.machine_user_tags.created_at IS '创建时间';

