-- Add migration script here
-- public.gray_releases definition

-- Drop table
-- DROP TABLE public.gray_releases;

CREATE TABLE public.gray_releases (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	name varchar(100) NOT NULL, -- 灰度名称
	description text NULL, -- 描述
	platform varchar(50) NOT NULL, -- 平台
	status varchar(20) DEFAULT 'pending'::character varying NOT NULL, -- 状态
	start_time timestamptz NOT NULL, -- 开始时间
	end_time timestamptz NULL, -- 结束时间
	max_machines int4 NULL, -- 最大配额（NULL=不限制）
	allocated_count int4 DEFAULT 0 NOT NULL, -- 已分配数量
	priority int4 DEFAULT 0 NOT NULL, -- 优先级
	strategy_type varchar(50) NULL, -- 策略类型
	strategy_config jsonb NULL, -- 策略配置（JSON格式）
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 创建时间
	updated_at timestamptz NULL, -- 更新时间
	CONSTRAINT gray_releases_pk PRIMARY KEY (id)
);
CREATE INDEX gray_releases_status_idx ON public.gray_releases USING btree (status);
CREATE INDEX gray_releases_platform_idx ON public.gray_releases USING btree (platform);
CREATE INDEX gray_releases_time_idx ON public.gray_releases USING btree (start_time, end_time);
CREATE INDEX gray_releases_priority_idx ON public.gray_releases USING btree (priority);

-- Column comments
COMMENT ON COLUMN public.gray_releases.id IS '主键ID';
COMMENT ON COLUMN public.gray_releases.name IS '灰度名称';
COMMENT ON COLUMN public.gray_releases.description IS '描述';
COMMENT ON COLUMN public.gray_releases.platform IS '平台';
COMMENT ON COLUMN public.gray_releases.status IS '状态';
COMMENT ON COLUMN public.gray_releases.start_time IS '开始时间';
COMMENT ON COLUMN public.gray_releases.end_time IS '结束时间';
COMMENT ON COLUMN public.gray_releases.max_machines IS '最大配额（NULL=不限制）';
COMMENT ON COLUMN public.gray_releases.allocated_count IS '已分配数量';
COMMENT ON COLUMN public.gray_releases.priority IS '优先级';
COMMENT ON COLUMN public.gray_releases.strategy_type IS '策略类型';
COMMENT ON COLUMN public.gray_releases.strategy_config IS '策略配置（JSON格式）';
COMMENT ON COLUMN public.gray_releases.created_at IS '创建时间';
COMMENT ON COLUMN public.gray_releases.updated_at IS '更新时间';

