-- Add migration script here
-- public.strategy_types definition

-- Drop table
-- DROP TABLE public.strategy_types;

CREATE TABLE public.strategy_types (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	code varchar(50) NOT NULL, -- 策略代码（对应 Rust 枚举值）
	name varchar(100) NOT NULL, -- 策略名称
	category varchar(50) NULL, -- 分类
	description text NULL, -- 描述
	processor_type varchar(50) NOT NULL, -- 处理器类型（对应 ProcessorType 枚举）
	config_schema text NULL, -- 配置JSON Schema
	is_active bool DEFAULT true NOT NULL, -- 是否激活
	CONSTRAINT strategy_types_pk PRIMARY KEY (id),
	CONSTRAINT strategy_types_code_unique UNIQUE (code)
);
CREATE UNIQUE INDEX strategy_types_code_idx ON public.strategy_types USING btree (code);
CREATE INDEX strategy_types_category_idx ON public.strategy_types USING btree (category);

-- Column comments
COMMENT ON COLUMN public.strategy_types.id IS '主键ID';
COMMENT ON COLUMN public.strategy_types.code IS '策略代码（对应 Rust 枚举值）';
COMMENT ON COLUMN public.strategy_types.name IS '策略名称';
COMMENT ON COLUMN public.strategy_types.category IS '分类';
COMMENT ON COLUMN public.strategy_types.description IS '描述';
COMMENT ON COLUMN public.strategy_types.processor_type IS '处理器类型（对应 ProcessorType 枚举）';
COMMENT ON COLUMN public.strategy_types.config_schema IS '配置JSON Schema';
COMMENT ON COLUMN public.strategy_types.is_active IS '是否激活';

