-- Add migration script here
-- public.machine_gray_allocations definition

-- Drop table
-- DROP TABLE public.machine_gray_allocations;

CREATE TABLE public.machine_gray_allocations (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	machine_code varchar(255) NOT NULL, -- 机器码
	gray_release_id int4 NOT NULL, -- 灰度发布ID
	allocated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 分配时间
	effective_time timestamptz NULL, -- 生效时间
	status varchar(20) DEFAULT 'active'::character varying NOT NULL, -- 状态
	notes text NULL, -- 备注
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 创建时间
	CONSTRAINT machine_gray_allocations_pk PRIMARY KEY (id),
	CONSTRAINT machine_gray_allocations_machine_gray_unique UNIQUE (machine_code, gray_release_id),
	CONSTRAINT machine_gray_allocations_gray_release_id_fk FOREIGN KEY (gray_release_id) REFERENCES public.gray_releases(id)
);
CREATE INDEX machine_gray_allocations_machine_code_idx ON public.machine_gray_allocations USING btree (machine_code);
CREATE INDEX machine_gray_allocations_gray_release_id_idx ON public.machine_gray_allocations USING btree (gray_release_id);
CREATE INDEX machine_gray_allocations_status_idx ON public.machine_gray_allocations USING btree (status);

-- Column comments
COMMENT ON COLUMN public.machine_gray_allocations.id IS '主键ID';
COMMENT ON COLUMN public.machine_gray_allocations.machine_code IS '机器码';
COMMENT ON COLUMN public.machine_gray_allocations.gray_release_id IS '灰度发布ID';
COMMENT ON COLUMN public.machine_gray_allocations.allocated_at IS '分配时间';
COMMENT ON COLUMN public.machine_gray_allocations.effective_time IS '生效时间';
COMMENT ON COLUMN public.machine_gray_allocations.status IS '状态';
COMMENT ON COLUMN public.machine_gray_allocations.notes IS '备注';
COMMENT ON COLUMN public.machine_gray_allocations.created_at IS '创建时间';

