import React, { useEffect, useState } from 'react';
import { AppLayout } from './app/components/AppLayout';
import { pluginRegistry, pluginLoader, setPluginImportFunctions } from '@slotkitjs/core';

// Import generated plugin import mappings
// This file is generated by 'slotkit generate-imports'
import * as pluginImports from './core/plugin/loader/plugin-imports.generated';

const MAIN_STARTUP_PLUGIN_IDS = [
  'app-layout',
  'authorization-layout',
  'environment-manager',
  'login',
  'register',
  'i18n',
  'store',
  'window-manager',
] as const;

const MODE_PLUGIN_IDS = {
  main: MAIN_STARTUP_PLUGIN_IDS,
  syncer: ['syncer'],
} as const;

const MAIN_WINDOW_READY_EVENT = 'simprint:main-window-ready';

// Initialize plugin import mappings
if (pluginImports.getPluginImport && pluginImports.getAvailablePluginIds) {
  setPluginImportFunctions({
    // @deprecated Compatibility adapter for generated mappings from
    // @slotkitjs/core < 0.3.5. Remove after all consumers generate Promise-based imports.
    getPluginImport: (pluginId: string) => {
      const importPlugin = pluginImports.getPluginImport(pluginId);
      return importPlugin ? () => Promise.resolve(importPlugin()) : undefined;
    },
    getAvailablePluginIds: pluginImports.getAvailablePluginIds,
    getAllPluginManifests: pluginImports.getAllPluginManifests,
    getPluginManifest: pluginImports.getPluginManifest,
  });
} else {
  console.warn('[WARN] Plugin import functions not found in generated file');
}

const loadPlugins = async (pluginIds: readonly string[]) => {
  try {
    const selectivePluginLoader = pluginLoader as typeof pluginLoader & {
      loadPlugins?: (ids: readonly string[]) => ReturnType<typeof pluginLoader.loadAllPlugins>;
    };

    // @deprecated Compatibility fallback for @slotkitjs/core < 0.3.5.
    // Remove after Simprint's lockfile is upgraded to a published 0.3.5+ release.
    const plugins = selectivePluginLoader.loadPlugins
      ? await selectivePluginLoader.loadPlugins(pluginIds)
      : await pluginLoader.loadAllPlugins();

    plugins.forEach((plugin) => {
      if (!pluginRegistry.getPlugin(plugin.id)) {
        pluginRegistry.register(plugin);
      }
    });

    return plugins;
  } catch (error) {
    console.error('[ERROR] Failed to load plugins:', error);
    return [];
  }
};

interface AppProps {
  /**
   * 应用模式：'main' 渲染主应用布局，'syncer' 渲染同步器窗口
   */
  mode?: 'main' | 'syncer';
}

const App: React.FC<AppProps> = ({ mode = 'main' }) => {
  const [pluginsReady, setPluginsReady] = useState(false);

  useEffect(() => {
    let cancelled = false;
    let idleCallbackId: number | undefined;

    const loadDeferredPlugins = () => {
      const startupPlugins = new Set<string>(MAIN_STARTUP_PLUGIN_IDS);
      const deferredPluginIds = pluginImports
        .getAvailablePluginIds()
        .filter((pluginId) => !startupPlugins.has(pluginId) && pluginId !== 'syncer');

      const startLoading = () => {
        void loadPlugins(deferredPluginIds).then(() => {
          console.log('[App] Deferred plugins loaded');
        });
      };

      if ('requestIdleCallback' in window) {
        idleCallbackId = window.requestIdleCallback(startLoading, { timeout: 2000 });
      } else {
        idleCallbackId = window.setTimeout(startLoading, 0);
      }
    };

    if (mode === 'main') {
      window.addEventListener(MAIN_WINDOW_READY_EVENT, loadDeferredPlugins, { once: true });
    }

    loadPlugins(MODE_PLUGIN_IDS[mode])
      .then(() => {
        console.log('[App] Plugins loaded for mode:', mode);
        if (!cancelled) setPluginsReady(true);
      })
      .catch((error) => {
        console.error('[ERROR] Failed to load plugins:', error);
        if (!cancelled) setPluginsReady(true);
      });

    return () => {
      cancelled = true;
      window.removeEventListener(MAIN_WINDOW_READY_EVENT, loadDeferredPlugins);
      if (idleCallbackId !== undefined) {
        if ('cancelIdleCallback' in window) {
          window.cancelIdleCallback(idleCallbackId);
        } else {
          window.clearTimeout(idleCallbackId);
        }
      }
    };
  }, [mode]);

  return (
    <div className="app">
      <AppLayout mode={mode} pluginsReady={pluginsReady} />
    </div>
  );
};

export default App;
